---
galaxy_info:
  author: Pierre Paul Lefebvre
  description: 
  company: Pheromone
  license: Apache v2
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - web
dependencies: []
